version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}  # Redis 비밀번호 환경변수
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]  # Redis에서 비밀번호 요구
    networks:
      - my_network

  mongodb:
    image: mongo:8.0  # MongoDB 8.0 버전 이미지
    container_name: mongo_container
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}  # MongoDB admin ID 환경변수
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}  # MongoDB admin 비밀번호 환경변수
    ports:
      - "27017:27017"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
